deployment:
  tasks:
    # Define the deployment 
    - export DEPLOYPATH=/home/lionsdes/public_html/

    # Sync repository to public_html, excluding .git and Uploads (optional)
    - /bin/rsync -av --exclude '.git' --exclude 'Uploads' /home/lionsdes/repositories/lionsdesign/ $DEPLOYPATH >> /home/lionsdes/deploy.log 2>&1
